github: [binaryconstruct]
patreon: binaryconstruct
ko_fi: binaryconstruct
custom: [ 'https://www.buymeacoffee.com/binaryconstruct', 'https://www.subscribestar.com/binaryconstruct', 'https://www.buymeacoffee.com/cokolele']